### ISSUE TITLE
__unused warning

### ISSUE THREAD

**Issue by ZevEisenberg** [Raizlabs/RZDataBinding#13]
Recommend using these warnings for the sample project:

`-Weverything -Wno-objc-missing-property-synthesis -Wno-objc-property-synthesis -Wno-direct-ivar-access -Wno-assign-enum -Wno-float-equal -Wno-sign-compare -Wno-switch-enum -Wno-gnu -Wnewline-eof`

**Comment by ZevEisenberg** [comment]
It would also nice to replace `c` → `Class` and `p` → `keyPath`.

**Comment by jvisenti** [comment]
Fixed in 1.2.0
