### ISSUE TITLE
Helper macro for `keyPathsForValuesAffecting`

### ISSUE THREAD

**Issue by KingOfBrian** [Raizlabs/RZDataBinding#18]
I find myself writing this a lot:
```objc
+ (NSSet *)keyPathsForValuesAffectingMyKeyPath
{
    return [NSSet setWithObjects:
            RZDB_KP(ClassName, self.key.path.1),
            RZDB_KP(ClassNmae, self.key.path.2),
            nil];
}
```

It would be awesome to have a macro that would:

```objc
RZDB_KEYPATHS_AFFECTING( MyKeyPath, ClassName, self.key.path.1, self.key.path.2)
```

**Comment by ZevEisenberg** [comment]
:+1: agreed

**Comment by jvisenti** [comment]
After actually implementing this, it looks like:
```
#define RZDB_KEYPATHS_AFFECTING(CapitalizedKeyPath, ...) \
+ (NSSet *)keyPathsForValuesAffecting##CapitalizedKeyPath \
{ \
    return [NSSet setWithObjects:__VA_ARGS__, nil]; \
}
```
Usage:
`RZDB_KEYPATHS_AFFECTING(MyKeyPath, RZDB_KP(MyClass, affectingKeyPath), ...)`

**Comment by jvisenti** [comment]
Since that's not the greatest code savings and may introduce confusion, I vote that we close this issue. Thoughts @ZevEisenberg ?

**Comment by ZevEisenberg** [comment]
Yep. It doesn't seem to save any significant amount of typing, and makes code a little more difficult to read.

**Comment by jvisenti** [comment]
Closing unless we come up with a better solution, or find a pressing need for something like this.
