### ISSUE TITLE
Document binding nil values to primitive types

### ISSUE THREAD

**Issue by KingOfBrian** [Raizlabs/RZDataBinding#20]
If `rz_bind` is used to bind to a primitive value, the  `withFunction:` version must be used to properly handle `nil` values.

**Comment by jvisenti** [comment]
@KingOfBrian How would you feel about nil values always being passed up as `@(0)` for primitive types when a `nil` is encountered? RZDB can do that conversion.

**Comment by jvisenti** [comment]
Provided documentation for this, and several transforms for convenience
