### ISSUE TITLE
bind should not emit changes for equal values

### ISSUE THREAD

**Issue by KingOfBrian** [Raizlabs/RZDataBinding#24]
If a property is set to the same value 5 times, only 1 set value should occur.

**Comment by jvisenti** [comment]
@KingOfBrian Do you think this behavior should extend to `rz_addTarget:action:`?
It will also add a bit of overhead to first `valueForKey:` and then `isEqual:` the values, but that may not be  terribly impactful.

**Comment by jvisenti** [comment]
Fixed on develop.
