### ISSUE TITLE
rz_addTarget:action:forKeyPathChange: is considered an unrecognised selector

### ISSUE THREAD

**Issue by miguelgazela** [Raizlabs/RZDataBinding#47]
I'm trying to use the RZDataBinding library to observe changes in a property of a NSObject. I have the following code:

```objc
[self rz_addTarget:self action:@selector(senderDidChange:) forKeyPathChange:RZDB_KP_SELF(sender)];
```

It compiles, but when it tries to run it throws an error of unrecognised selector being sent to the instance. The `self`object is a direct subclass of NSObject.

Any idea what is going wrong here?

**Comment by jvisenti** [comment]
Hey @miguelgazela, I haven't seen this problem before. I have had an issue in the past though where methods added in a category were being "unrecognized" at runtime. The solution in that case was to remove the category from the project and re-add (though probably just ensuring that the .m was in the compiled sources may have been sufficient).

How are you integrating `RZDataBinding`? Is it via Cocoapods?

**Comment by jvisenti** [comment]
@miguelgazela Has this issue been resolved for you?
